-- MySQL Script generated by MySQL Workbench
-- Sun Sep 24 09:34:36 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema apocalypse_reborn
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema apocalypse_reborn
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `apocalypse_reborn` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema apocalypse_reborn
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema apocalypse_reborn
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `apocalypse_reborn` DEFAULT CHARACTER SET utf8 ;
USE `apocalypse_reborn` ;

-- -----------------------------------------------------
-- Table `apocalypse_reborn`.`ethnicity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apocalypse_reborn`.`ethnicity` (
  `id_ethnicity` INT(11) NOT NULL,
  `label` VARCHAR(45) NULL DEFAULT NULL,
  `display_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_ethnicity`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apocalypse_reborn`.`gender`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apocalypse_reborn`.`gender` (
  `id_gender` INT(11) NOT NULL,
  `label` VARCHAR(45) NULL DEFAULT NULL,
  `display_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_gender`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apocalypse_reborn`.`firstname`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apocalypse_reborn`.`firstname` (
  `id_firstname` INT(11) NOT NULL,
  `label` VARCHAR(45) NULL DEFAULT NULL,
  `ethnicity_id_ethnicity` INT(11) NOT NULL,
  `gender_id_gender` INT(11) NOT NULL,
  PRIMARY KEY (`id_firstname`),
  INDEX `fk_firstname_ethnicity1_idx` (`ethnicity_id_ethnicity` ASC) ,
  INDEX `fk_firstname_gender1_idx` (`gender_id_gender` ASC) ,
  CONSTRAINT `fk_firstname_ethnicity1`
    FOREIGN KEY (`ethnicity_id_ethnicity`)
    REFERENCES `apocalypse_reborn`.`ethnicity` (`id_ethnicity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_firstname_gender1`
    FOREIGN KEY (`gender_id_gender`)
    REFERENCES `apocalypse_reborn`.`gender` (`id_gender`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apocalypse_reborn`.`lastname`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apocalypse_reborn`.`lastname` (
  `id_lastname` INT(11) NOT NULL,
  `label` VARCHAR(45) NULL DEFAULT NULL,
  `ethnicity_id_ethnicity` INT(11) NOT NULL,
  PRIMARY KEY (`id_lastname`, `ethnicity_id_ethnicity`),
  INDEX `fk_lastname_ethnicity1_idx` (`ethnicity_id_ethnicity` ASC) ,
  CONSTRAINT `fk_lastname_ethnicity1`
    FOREIGN KEY (`ethnicity_id_ethnicity`)
    REFERENCES `apocalypse_reborn`.`ethnicity` (`id_ethnicity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apocalypse_reborn`.`work`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apocalypse_reborn`.`work` (
  `id_work` INT(11) NOT NULL,
  `label` VARCHAR(45) NOT NULL,
  `logo_work` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_work`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apocalypse_reborn`.`list_gender_work`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apocalypse_reborn`.`list_gender_work` (
  `id_list_gender_work` INT(11) NOT NULL,
  `work_name` VARCHAR(45) NULL DEFAULT NULL,
  `gender_id_gender` INT(11) NOT NULL,
  `work_id_work` INT(11) NOT NULL,
  PRIMARY KEY (`id_list_gender_work`),
  INDEX `fk_liste_gender_work_gender1_idx` (`gender_id_gender` ASC) ,
  INDEX `fk_liste_gender_work_work1_idx` (`work_id_work` ASC) ,
  CONSTRAINT `fk_liste_gender_work_gender1`
    FOREIGN KEY (`gender_id_gender`)
    REFERENCES `apocalypse_reborn`.`gender` (`id_gender`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_liste_gender_work_work1`
    FOREIGN KEY (`work_id_work`)
    REFERENCES `apocalypse_reborn`.`work` (`id_work`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apocalypse_reborn`.`photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apocalypse_reborn`.`photo` (
  `id_photo` INT(11) NOT NULL,
  `src` VARCHAR(45) NULL DEFAULT NULL,
  `alt` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_photo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apocalypse_reborn`.`nationality`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apocalypse_reborn`.`nationality` (
  `id_nationnality` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(45) NULL,
  `display_name_fr` VARCHAR(45) NULL,
  PRIMARY KEY (`id_nationnality`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apocalypse_reborn`.`pnj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apocalypse_reborn`.`pnj` (
  `id_pnj` INT(11) NOT NULL,
  `level` INT(11) NULL DEFAULT NULL,
  `exp` INT(11) NULL DEFAULT NULL,
  `gender_id_gender` INT(11) NOT NULL,
  `ethnicity_id_ethnicity` INT(11) NOT NULL,
  `photo_id_photo` INT(11) NOT NULL,
  `work_id_work` INT(11) NOT NULL,
  `firstname_id_firstname` INT(11) NOT NULL,
  `lastname_id_lastname` INT(11) NOT NULL,
  `nationality_id_nationnality` INT NOT NULL,
  PRIMARY KEY (`id_pnj`),
  INDEX `fk_pnj_gender_idx` (`gender_id_gender` ASC) ,
  INDEX `fk_pnj_ethnicity1_idx` (`ethnicity_id_ethnicity` ASC) ,
  INDEX `fk_pnj_photo1_idx` (`photo_id_photo` ASC) ,
  INDEX `fk_pnj_work1_idx` (`work_id_work` ASC) ,
  INDEX `fk_pnj_firstname1_idx` (`firstname_id_firstname` ASC) ,
  INDEX `fk_pnj_lastname1_idx` (`lastname_id_lastname` ASC) ,
  INDEX `fk_pnj_nationality1_idx` (`nationality_id_nationnality` ASC) ,
  CONSTRAINT `fk_pnj_ethnicity1`
    FOREIGN KEY (`ethnicity_id_ethnicity`)
    REFERENCES `apocalypse_reborn`.`ethnicity` (`id_ethnicity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pnj_firstname1`
    FOREIGN KEY (`firstname_id_firstname`)
    REFERENCES `apocalypse_reborn`.`firstname` (`id_firstname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pnj_gender`
    FOREIGN KEY (`gender_id_gender`)
    REFERENCES `apocalypse_reborn`.`gender` (`id_gender`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pnj_lastname1`
    FOREIGN KEY (`lastname_id_lastname`)
    REFERENCES `apocalypse_reborn`.`lastname` (`id_lastname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pnj_photo1`
    FOREIGN KEY (`photo_id_photo`)
    REFERENCES `apocalypse_reborn`.`photo` (`id_photo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pnj_work1`
    FOREIGN KEY (`work_id_work`)
    REFERENCES `apocalypse_reborn`.`work` (`id_work`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pnj_nationality1`
    FOREIGN KEY (`nationality_id_nationnality`)
    REFERENCES `apocalypse_reborn`.`nationality` (`id_nationnality`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apocalypse_reborn`.`skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apocalypse_reborn`.`skills` (
  `id_skills` INT(11) NOT NULL,
  `strength` INT(11) NULL DEFAULT NULL,
  `agility` INT(11) NULL DEFAULT NULL,
  `stealth` INT(11) NULL DEFAULT NULL,
  `intelligence` INT(11) NULL DEFAULT NULL,
  `charisma` INT(11) NULL DEFAULT NULL,
  `accuracy` INT(11) NULL DEFAULT NULL,
  `perception` INT(11) NULL DEFAULT NULL,
  `survival` INT(11) NOT NULL,
  `pnj_id_pnj` INT(11) NOT NULL,
  PRIMARY KEY (`id_skills`),
  INDEX `fk_skills_pnj1_idx` (`pnj_id_pnj` ASC) ,
  CONSTRAINT `fk_skills_pnj1`
    FOREIGN KEY (`pnj_id_pnj`)
    REFERENCES `apocalypse_reborn`.`pnj` (`id_pnj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apocalypse_reborn`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apocalypse_reborn`.`users` (
  `id_users` INT(11) NOT NULL,
  `login` VARCHAR(64) NULL DEFAULT NULL,
  `password` VARCHAR(512) NULL DEFAULT NULL,
  `level` INT(11) NOT NULL,
  `exp` INT(11) NOT NULL,
  PRIMARY KEY (`id_users`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `apocalypse_reborn` ;

-- -----------------------------------------------------
-- Table `apocalypse_reborn`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apocalypse_reborn`.`users` (
  `id_users` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(64) NULL DEFAULT NULL,
  `password` VARCHAR(512) NULL DEFAULT NULL,
  PRIMARY KEY (`id_users`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apocalypse_reborn`.`gender`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apocalypse_reborn`.`gender` (
  `id_gender` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(45) NULL DEFAULT NULL,
  `display_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_gender`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apocalypse_reborn`.`ethnicity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apocalypse_reborn`.`ethnicity` (
  `id_ethnicity` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(45) NULL DEFAULT NULL,
  `display_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_ethnicity`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apocalypse_reborn`.`photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apocalypse_reborn`.`photo` (
  `id_photo` INT NOT NULL AUTO_INCREMENT,
  `src` VARCHAR(45) NULL DEFAULT NULL,
  `alt` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_photo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apocalypse_reborn`.`work`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apocalypse_reborn`.`work` (
  `id_work` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_work`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apocalypse_reborn`.`pnj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apocalypse_reborn`.`pnj` (
  `id_pnj` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL DEFAULT NULL,
  `lastname` VARCHAR(45) NULL DEFAULT NULL,
  `level` INT NULL DEFAULT NULL,
  `exp` INT NULL DEFAULT NULL,
  `gender_id_gender` INT NOT NULL,
  `ethnicity_id_ethnicity` INT NOT NULL,
  `photo_id_photo` INT NOT NULL,
  `work_id_work` INT NOT NULL,
  PRIMARY KEY (`id_pnj`),
  INDEX `fk_pnj_gender_idx` (`gender_id_gender` ASC) ,
  INDEX `fk_pnj_ethnicity1_idx` (`ethnicity_id_ethnicity` ASC) ,
  INDEX `fk_pnj_photo1_idx` (`photo_id_photo` ASC) ,
  INDEX `fk_pnj_work1_idx` (`work_id_work` ASC) ,
  CONSTRAINT `fk_pnj_gender`
    FOREIGN KEY (`gender_id_gender`)
    REFERENCES `apocalypse_reborn`.`gender` (`id_gender`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pnj_ethnicity1`
    FOREIGN KEY (`ethnicity_id_ethnicity`)
    REFERENCES `apocalypse_reborn`.`ethnicity` (`id_ethnicity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pnj_photo1`
    FOREIGN KEY (`photo_id_photo`)
    REFERENCES `apocalypse_reborn`.`photo` (`id_photo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pnj_work1`
    FOREIGN KEY (`work_id_work`)
    REFERENCES `apocalypse_reborn`.`work` (`id_work`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apocalypse_reborn`.`skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apocalypse_reborn`.`skills` (
  `id_skills` INT NOT NULL AUTO_INCREMENT,
  `strength` INT NULL DEFAULT NULL,
  `agility` INT NULL DEFAULT NULL,
  `stealth` INT NULL DEFAULT NULL,
  `intelligence` INT NULL DEFAULT NULL,
  `charisma` INT NULL DEFAULT NULL,
  `precision` INT NULL DEFAULT NULL,
  `perception` INT NULL DEFAULT NULL,
  `survival` VARCHAR(45) NULL DEFAULT NULL,
  `pnj_id_pnj` INT NOT NULL,
  PRIMARY KEY (`id_skills`),
  INDEX `fk_skills_pnj1_idx` (`pnj_id_pnj` ASC) ,
  CONSTRAINT `fk_skills_pnj1`
    FOREIGN KEY (`pnj_id_pnj`)
    REFERENCES `apocalypse_reborn`.`pnj` (`id_pnj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apocalypse_reborn`.`list_gender_work`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apocalypse_reborn`.`list_gender_work` (
  `work_name` VARCHAR(45) NULL DEFAULT NULL,
  `gender_id_gender` INT NOT NULL,
  `work_id_work` INT NOT NULL,
  INDEX `fk_liste_gender_work_gender1_idx` (`gender_id_gender` ASC) ,
  INDEX `fk_liste_gender_work_work1_idx` (`work_id_work` ASC) ,
  CONSTRAINT `fk_liste_gender_work_gender1`
    FOREIGN KEY (`gender_id_gender`)
    REFERENCES `apocalypse_reborn`.`gender` (`id_gender`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_liste_gender_work_work1`
    FOREIGN KEY (`work_id_work`)
    REFERENCES `apocalypse_reborn`.`work` (`id_work`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apocalypse_reborn`.`ethnicDistributionByNationality`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apocalypse_reborn`.`ethnicDistributionByNationality` (
  `nationality_id_nationnality` INT NOT NULL,
  `ethnicity_id_ethnicity` INT(11) NOT NULL,
  `percentage` FLOAT NULL,
  PRIMARY KEY (`nationality_id_nationnality`, `ethnicity_id_ethnicity`),
  INDEX `fk_nationality_has_ethnicity_ethnicity1_idx` (`ethnicity_id_ethnicity` ASC) ,
  INDEX `fk_nationality_has_ethnicity_nationality1_idx` (`nationality_id_nationnality` ASC) ,
  CONSTRAINT `fk_nationality_has_ethnicity_nationality1`
    FOREIGN KEY (`nationality_id_nationnality`)
    REFERENCES `apocalypse_reborn`.`nationality` (`id_nationnality`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nationality_has_ethnicity_ethnicity1`
    FOREIGN KEY (`ethnicity_id_ethnicity`)
    REFERENCES `apocalypse_reborn`.`ethnicity` (`id_ethnicity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `apocalypse_reborn` ;