-- MySQL Script generated by MySQL Workbench
-- Mon Oct  2 19:48:30 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`suborigin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`suborigin` (
  `id_suborigin` INT(11) NOT NULL,
  `label` VARCHAR(45) NULL DEFAULT NULL,
  `display_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_suborigin`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`gender`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`gender` (
  `id_gender` INT(11) NOT NULL,
  `label` VARCHAR(45) NULL DEFAULT NULL,
  `display_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_gender`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`firstname`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`firstname` (
  `id_firstname` INT(11) NOT NULL,
  `label` VARCHAR(45) NULL DEFAULT NULL,
  `suborigin_id_suborigin` INT(11) NOT NULL,
  `gender_id_gender` INT(11) NOT NULL,
  PRIMARY KEY (`id_firstname`),
  INDEX `fk_firstname_ethnicity1_idx` (`suborigin_id_suborigin` ASC) VISIBLE,
  INDEX `fk_firstname_gender1_idx` (`gender_id_gender` ASC) VISIBLE,
  CONSTRAINT `fk_firstname_ethnicity1`
    FOREIGN KEY (`suborigin_id_suborigin`)
    REFERENCES `mydb`.`suborigin` (`id_suborigin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_firstname_gender1`
    FOREIGN KEY (`gender_id_gender`)
    REFERENCES `mydb`.`gender` (`id_gender`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`lastname`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lastname` (
  `id_lastname` INT(11) NOT NULL,
  `label` VARCHAR(45) NULL DEFAULT NULL,
  `suborigin_id_suborigin` INT(11) NOT NULL,
  PRIMARY KEY (`id_lastname`, `suborigin_id_suborigin`),
  INDEX `fk_lastname_ethnicity1_idx` (`suborigin_id_suborigin` ASC) VISIBLE,
  CONSTRAINT `fk_lastname_ethnicity1`
    FOREIGN KEY (`suborigin_id_suborigin`)
    REFERENCES `mydb`.`suborigin` (`id_suborigin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`work`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`work` (
  `id_work` INT(11) NOT NULL,
  `label` VARCHAR(45) NOT NULL,
  `logo_work` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_work`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`list_gender_work`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`list_gender_work` (
  `id_list_gender_work` INT(11) NOT NULL,
  `work_name` VARCHAR(45) NULL DEFAULT NULL,
  `gender_id_gender` INT(11) NOT NULL,
  `work_id_work` INT(11) NOT NULL,
  PRIMARY KEY (`id_list_gender_work`),
  INDEX `fk_liste_gender_work_gender1_idx` (`gender_id_gender` ASC) VISIBLE,
  INDEX `fk_liste_gender_work_work1_idx` (`work_id_work` ASC) VISIBLE,
  CONSTRAINT `fk_liste_gender_work_gender1`
    FOREIGN KEY (`gender_id_gender`)
    REFERENCES `mydb`.`gender` (`id_gender`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_liste_gender_work_work1`
    FOREIGN KEY (`work_id_work`)
    REFERENCES `mydb`.`work` (`id_work`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`species`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`species` (
  `id_species` INT(11) NOT NULL,
  `label` VARCHAR(45) NULL DEFAULT NULL,
  `display_name_fr` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_species`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`origin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`origin` (
  `id_origin` INT(11) NOT NULL,
  `label` VARCHAR(45) NULL DEFAULT NULL,
  `display_name_fr` VARCHAR(45) NULL DEFAULT NULL,
  `flag` VARCHAR(45) NOT NULL,
  `species_id` INT(11) NOT NULL,
  `has_suborigin` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_origin`),
  INDEX `species_id` (`species_id` ASC) VISIBLE,
  CONSTRAINT `origin_ibfk_1`
    FOREIGN KEY (`species_id`)
    REFERENCES `mydb`.`species` (`id_species`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`photo` (
  `id_photo` INT(11) NOT NULL,
  `src` VARCHAR(45) NULL DEFAULT NULL,
  `alt` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_photo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`pnj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pnj` (
  `id_pnj` INT(11) NOT NULL,
  `level` INT(11) NULL DEFAULT NULL,
  `exp` INT(11) NULL DEFAULT NULL,
  `gender_id_gender` INT(11) NOT NULL,
  `ethnicity_id_ethnicity` INT(11) NOT NULL,
  `photo_id_photo` INT(11) NOT NULL,
  `work_id_work` INT(11) NOT NULL,
  `firstname_id_firstname` INT(11) NOT NULL,
  `lastname_id_lastname` INT(11) NOT NULL,
  `nationality_id_nationnality` INT(11) NOT NULL,
  PRIMARY KEY (`id_pnj`),
  INDEX `fk_pnj_gender_idx` (`gender_id_gender` ASC) VISIBLE,
  INDEX `fk_pnj_ethnicity1_idx` (`ethnicity_id_ethnicity` ASC) VISIBLE,
  INDEX `fk_pnj_photo1_idx` (`photo_id_photo` ASC) VISIBLE,
  INDEX `fk_pnj_work1_idx` (`work_id_work` ASC) VISIBLE,
  INDEX `fk_pnj_firstname1_idx` (`firstname_id_firstname` ASC) VISIBLE,
  INDEX `fk_pnj_lastname1_idx` (`lastname_id_lastname` ASC) VISIBLE,
  INDEX `fk_pnj_nationality1_idx` (`nationality_id_nationnality` ASC) VISIBLE,
  CONSTRAINT `fk_pnj_ethnicity1`
    FOREIGN KEY (`ethnicity_id_ethnicity`)
    REFERENCES `mydb`.`suborigin` (`id_suborigin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pnj_gender`
    FOREIGN KEY (`gender_id_gender`)
    REFERENCES `mydb`.`gender` (`id_gender`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pnj_nationality1`
    FOREIGN KEY (`nationality_id_nationnality`)
    REFERENCES `mydb`.`origin` (`id_origin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pnj_photo1`
    FOREIGN KEY (`photo_id_photo`)
    REFERENCES `mydb`.`photo` (`id_photo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pnj_work1`
    FOREIGN KEY (`work_id_work`)
    REFERENCES `mydb`.`work` (`id_work`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`skills` (
  `id_skills` INT(11) NOT NULL,
  `strength` INT(11) NULL DEFAULT NULL,
  `agility` INT(11) NULL DEFAULT NULL,
  `stealth` INT(11) NULL DEFAULT NULL,
  `intelligence` INT(11) NULL DEFAULT NULL,
  `charisma` INT(11) NULL DEFAULT NULL,
  `accuracy` INT(11) NULL DEFAULT NULL,
  `perception` INT(11) NULL DEFAULT NULL,
  `survival` INT(11) NOT NULL,
  `pnj_id_pnj` INT(11) NOT NULL,
  PRIMARY KEY (`id_skills`),
  INDEX `fk_skills_pnj1_idx` (`pnj_id_pnj` ASC) VISIBLE,
  CONSTRAINT `fk_skills_pnj1`
    FOREIGN KEY (`pnj_id_pnj`)
    REFERENCES `mydb`.`pnj` (`id_pnj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`suborigindistributionbyorigin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`suborigindistributionbyorigin` (
  `origin_id_origin` INT(11) NOT NULL,
  `suborigin_id_suborigin` INT(11) NOT NULL,
  `percentage` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`origin_id_origin`, `suborigin_id_suborigin`),
  INDEX `fk_nationality_has_ethnicity_ethnicity1_idx` (`suborigin_id_suborigin` ASC) VISIBLE,
  INDEX `fk_nationality_has_ethnicity_nationality1_idx` (`origin_id_origin` ASC) VISIBLE,
  CONSTRAINT `fk_nationality_has_ethnicity_ethnicity1`
    FOREIGN KEY (`suborigin_id_suborigin`)
    REFERENCES `mydb`.`suborigin` (`id_suborigin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nationality_has_ethnicity_nationality1`
    FOREIGN KEY (`origin_id_origin`)
    REFERENCES `mydb`.`origin` (`id_origin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`system`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`system` (
  `id_system` INT(11) NOT NULL,
  `label` VARCHAR(45) NULL DEFAULT NULL,
  `display_name_fr` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_system`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`system_species`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`system_species` (
  `system_id` INT(11) NOT NULL,
  `species_id` INT(11) NOT NULL,
  PRIMARY KEY (`system_id`, `species_id`),
  INDEX `species_id` (`species_id` ASC) VISIBLE,
  CONSTRAINT `system_species_ibfk_1`
    FOREIGN KEY (`system_id`)
    REFERENCES `mydb`.`system` (`id_system`)
    ON DELETE CASCADE,
  CONSTRAINT `system_species_ibfk_2`
    FOREIGN KEY (`species_id`)
    REFERENCES `mydb`.`species` (`id_species`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id_users` INT(11) NOT NULL,
  `login` VARCHAR(64) NULL DEFAULT NULL,
  `password` VARCHAR(512) NULL DEFAULT NULL,
  `level` INT(11) NOT NULL,
  `exp` INT(11) NOT NULL,
  PRIMARY KEY (`id_users`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `mydb` ;

-- -----------------------------------------------------
-- procedure CreateRandomPNJ
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
--
-- Procedures
--
CREATE DEFINER=`root`@`localhost` PROCEDURE `CreateRandomPNJ` ()   BEGIN
    DECLARE randomGenderID INT;
    DECLARE randomEthnicityID INT;
    DECLARE randomFirstname VARCHAR(45);
    DECLARE randomLastname VARCHAR(45);
    DECLARE randomPhotoID INT;
    DECLARE randomWorkID INT;

    -- Choisir un genre aléatoirement
    SET randomGenderID = (SELECT id_gender FROM gender ORDER BY RAND() LIMIT 1);

    -- Choisir une ethnie aléatoirement
    SET randomEthnicityID = (SELECT id_ethnicity FROM ethnicity ORDER BY RAND() LIMIT 1);

    -- Choisir un prénom en fonction de l'ethnie et du genre
    -- Remarque: Vous devrez ajuster cette requête en fonction de la structure réelle de votre base de données
    SET randomFirstname = (SELECT firstname FROM your_table_with_firstnames WHERE gender_id = randomGenderID AND ethnicity_id = randomEthnicityID ORDER BY RAND() LIMIT 1);

    -- Choisir un nom en fonction de l'ethnie
    -- Remarque: Vous devrez ajuster cette requête en fonction de la structure réelle de votre base de données
    SET randomLastname = (SELECT lastname FROM your_table_with_lastnames WHERE ethnicity_id = randomEthnicityID ORDER BY RAND() LIMIT 1);

    -- Choisir une photo en fonction de l'ethnie et du genre
    SET randomPhotoID = (SELECT id_photo FROM photo WHERE gender_id = randomGenderID AND ethnicity_id = randomEthnicityID ORDER BY RAND() LIMIT 1);

    -- Choisir un métier aléatoirement
    SET randomWorkID = (SELECT id_work FROM work ORDER BY RAND() LIMIT 1);

    -- Insérer le nouveau PNJ dans la table 'pnj'
    INSERT INTO pnj (firstname, lastname, gender_id_gender, ethnicity_id_ethnicity, photo_id_photo, work_id_work)
    VALUES (randomFirstname, randomLastname, randomGenderID, randomEthnicityID, randomPhotoID, randomWorkID);
    
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
